version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  web:
    image: cglass1982/backend    
    command: bash -c "python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"
    volumes: 
      - ./static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: cglass1982/frontend
    volumes:
      - react_build:/react/build
      - /react/node_modules
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf
      - react_build:/usr/share/nginx/html/
    depends_on:
      - web
      - frontend
volumes:
  react_build:

