name: Continuous Deployment

on:
  push: 
    branches:
      - master 


jobs:
  deployment:
    runs-on: self-hosted 
    steps:
      - name: Checkout main branch 
        uses: actions/checkout@v2
        with:
          clean: false 

      - name: Build and run docker containers
        run: |
          cd ~/root/test-docker/
          docker-compose up
