name: Continuous Deployment

on:
  push: 
    branches:
      - master 


jobs:
  deployment:
    runs-on: self-hosted 
    steps:
      - name: Checkout main branch 
        uses: actions/checkout@v2

      - name: Build and run docker containers
        run: |
          su - craig 
          chown -R craig ~/actions-runner/_work
          cd ~/actions-runner/_work/easymeals/easymeals 
          docker-compose up 
