name: Continuous Deployment

on:
  push: 
    branches:
      - master 


jobs:
  deployment:
    runs-on: self-hosted 
    steps:
      - name: Checkout main branch 
        uses: actions/checkout@v2

      - name: Build docker containers
<<<<<<< HEAD
        run: echo 'success!!'
=======
        run: echo success!!
>>>>>>> 79c9f6cdf4846b36f87b52426adfe138481f0e88
