name: Continuous Deployment

on:
  push: 
    branches:
      - master 


jobs:
  

  deployment:
    runs-on: self-hosted 
    steps:
      - name: Build and run docker containers
        run: |
          su - craig 
          cd ~/actions-runner/easymeals
          sudo docker-compose pull 
          sudo docker-compose up -d
